{% set name = "toolwrapper" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 128088c93cb02fcaa6701c488e62e027f45ca5597b5c9bcf28816ad70e830bf7

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - toolwrapper

about:
  home: https://bitbucket.org/luismsgomes/toolwrapper
  license: MIT
  license_family: MIT
  license_file: ./LICENSE
  summary: A base class for wrapping text-processing tools
  doc_url: https://bitbucket.org/luismsgomes/toolwrapper/src/default/README.rst

extra:
  recipe-maintainers:
    - monaldoj
