travis:
  secure:
    BINSTAR_TOKEN: cMu8SnOjotZ1JM0I76258nq3Nqd7PEw53ZPcWOxWQWViZrShKYL5LoG6QbJ3eCsJ5VBbVNf/kKQ63byDKHtJZQnxSoqf/bS07EBb7dinVNHtjPgRx4x1Hw/COfWNCBsPpCqS0bCnP0zeYRGrfiAM+v3Xt1Ca0CWUUgi8LD/Ew/aRFcc0ZuzBr8DdP1NY6LY4YpkjbzH3MGGhnsmUJRPeLZGKLEtRYCga572ZR6v2GNbi05dBIiu3uYo5b8f2I8ii1yT/fYZ4oZR4S1BBP9ggmBczAvIAmDdOcI6khAUgByJpHfdIwtbx6g9Nu/ju5gXChCmNZZAKUQaCRDOBmtGkc6IObt9SA7mjFC+yOgQ6TQ0P+Y7WyckUiJyp/SDf8kP97wUNjHiTZXBt+lXJBBJTl0y+T03Y4Zs6IIKWWcf6SUL9XgGyaTNFqZMN2jrrqKGuO2N9tWOKIb4qfn54OulWohc7sQVRC/VEeJBh7kOQ+VWiBPszZYk+AfSSxRro7LTn1rplr/N/urX3Ju/GAMXK3lUx4ePCx8VrDNN0nS2PFR+Ng3OkDOoGVBIBcrYpGdrrvSNdiRPdv2lljeMFJLsEtMdoCo1MTqMwLe3j5DPSIAbhV8nE6Js7hIR8i2BtQRqBl1mT+Jsb+CrMWitrhHswinBYU8j4SU740sni9Sa00cI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
